/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "background": "#101419",
        "surface": "#101419",
        "secondary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#400011",
        "on-surface-variant": "#e5bdc0",
        "on-tertiary-fixed-variant": "#005228",
        "on-secondary": "#00363a",
        "surface-variant": "#31353c",
        "secondary-fixed": "#7df4ff",
        "on-tertiary-fixed": "#00210c",
        "primary-fixed-dim": "#ffb2ba",
        "on-secondary-fixed": "#002022",
        "outline": "#ac888b",
        "on-tertiary": "#003919",
        "on-tertiary-container": "#003115",
        "primary": "#ffb2ba",
        "on-primary-container": "#5a001b",
        "surface-container-lowest": "#0b0e14",
        "secondary-container": "#00eefc",
        "on-secondary-fixed-variant": "#004f54",
        "tertiary-fixed": "#60ff99",
        "inverse-on-surface": "#2d3137",
        "primary-container": "#ff4f73",
        "on-background": "#e0e2eb",
        "surface-tint": "#ffb2ba",
        "on-surface": "#e0e2eb",
        "surface-container-low": "#181c22",
        "inverse-surface": "#e0e2eb",
        "on-error": "#690005",
        "surface-dim": "#101419",
        "on-secondary-container": "#00686f",
        "on-primary-fixed-variant": "#910030",
        "primary-fixed": "#ffd9dc",
        "tertiary-container": "#00a657",
        "tertiary-fixed-dim": "#00e479",
        "error": "#ffb4ab",
        "outline-variant": "#5c3f42",
        "secondary": "#d3fbff",
        "surface-container-highest": "#31353c",
        "surface-bright": "#363940",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#bd0042",
        "tertiary": "#00e479",
        "error-container": "#93000a",
        "on-primary": "#670020",
        "surface-container-high": "#262a31",
        "surface-container": "#1c2026",
        'surface-lowest': '#05080f',
        'surface-base': '#0a0f18',
        'surface-card': '#101726',
        'surface-border': '#1e293b',
        'hindsight-green': '#10b981',
        'hindsight-glow': '#00ff88',
        'sre-cyan': '#00f0ff',
        'decoy-red': '#ef4444',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "margin-mobile": "0.75rem",
        "gutter": "1rem",
        "margin": "1.5rem",
        "gutter-mobile": "0.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        mono: ['Space Mono', 'JetBrains Mono', 'ui-monospace', 'monospace'],
        sans: ['Space Grotesk', 'Inter', 'system-ui', 'sans-serif'],
        "label-lg": ["Space Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Mono", "monospace"],
        "label-sm": ["Space Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Mono", "monospace"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Mono", "monospace"],
        "label-md": ["Space Mono", "monospace"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["9px", { lineHeight: "12px", letterSpacing: "0.12em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "body-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
