"""Pydantic validation schemas and exception definitions for LLM inference.

Enforces strict schema validation on all structured responses produced by LLM providers,
preventing malformed JSON or invalid structures from propagating into the API response.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Pydantic Validation Schemas for Structured LLM Triage Output
# ---------------------------------------------------------------------------

class LLMRunbookActionSchema(BaseModel):
    """Schema for individual runbook steps generated by the LLM."""
    step_number: int = Field(default=1, description="Sequential step index")
    name: str = Field(..., description="Action title or procedure name")
    command: str = Field(default="# inspect status", description="Safe command or script")
    target_component: Optional[str] = Field(default=None, description="Target component or microservice")
    is_safe_simulation: bool = Field(default=True, description="Whether this action can be simulated safely")
    description: Optional[str] = Field(default="", description="Detailed step explanation")


class LLMRunbookSchema(BaseModel):
    """Schema for the mitigation runbook recommendation generated by the LLM."""
    runbook_id: str = Field(..., description="Standardized runbook identifier (e.g. RB-SERVICE-MITIGATION)")
    title: str = Field(..., description="Runbook title")
    justification: str = Field(..., description="Technical rationale grounded in evidence")
    historical_reference_id: Optional[str] = Field(default=None, description="Cited historical incident ID if applicable")
    blast_radius_analysis: Optional[str] = Field(default="", description="Blast radius and risk evaluation")
    actions: List[LLMRunbookActionSchema] = Field(default_factory=list, description="Ordered mitigation actions")


class LLMTriageOutputSchema(BaseModel):
    """Strict Pydantic validation schema for structured SRE triage inference.

    Every structured LLM response must validate against this model before
    being accepted by the triage orchestration pipeline.
    """
    incident_summary: str = Field(..., description="Executive summary of the incident")
    likely_root_cause: str = Field(..., description="Probable root cause hypothesis")
    supporting_evidence: List[str] = Field(default_factory=list, description="Factual supporting evidence bullets")
    recommended_runbook: Optional[LLMRunbookSchema] = Field(default=None, description="Recommended remediation runbook")
    failed_mitigations_to_avoid: List[str] = Field(default_factory=list, description="Anti-patterns to avoid")
    reasoning_summary: str = Field(..., description="SRE reasoning explanation")


# ---------------------------------------------------------------------------
# LLM Exception Hierarchy
# ---------------------------------------------------------------------------

class LLMError(Exception):
    """Base exception for all LLM inference errors."""
    pass


class LLMTimeoutError(LLMError):
    """Raised when an LLM provider call exceeds the configured request timeout."""
    def __init__(self, provider: str, timeout_seconds: float):
        super().__init__(f"LLM provider '{provider}' timed out after {timeout_seconds:.1f}s.")
        self.provider = provider
        self.timeout_seconds = timeout_seconds


class LLMMalformedJsonError(LLMError):
    """Raised when an LLM provider returns non-JSON or unparseable text."""
    def __init__(self, provider: str, raw_text: str, parse_error: str):
        preview = raw_text[:120] + "..." if len(raw_text) > 120 else raw_text
        super().__init__(f"LLM provider '{provider}' returned malformed JSON: {parse_error} (Preview: {preview!r})")
        self.provider = provider
        self.raw_text = raw_text
        self.parse_error = parse_error


class LLMSchemaValidationError(LLMError):
    """Raised when an LLM response is valid JSON but fails Pydantic schema validation."""
    def __init__(self, provider: str, validation_errors: Any):
        super().__init__(f"LLM provider '{provider}' output failed Pydantic schema validation: {validation_errors}")
        self.provider = provider
        self.validation_errors = validation_errors


class AllLLMProvidersFailedError(LLMError):
    """Raised when all configured primary and fallback LLM providers fail."""
    def __init__(self, provider_errors: Dict[str, str]):
        reasons = "; ".join(f"{p}: {err}" for p, err in provider_errors.items())
        super().__init__(f"All LLM providers failed: {reasons}")
        self.provider_errors = provider_errors
